### ISSUE TITLE
Need for consistent SCSS styling

### ISSUE THREAD

**Issue by andytambe31** [andytambe31/chef#5]
Using SCSS, we need to create a consistent, maintainable & documented stylesheets.

1. Under `libs` create a new directory `scss` that would hold the global styles
2. Under `scss` create the following directories, `abstracts`(representing the [design tokens](https://spectrum.adobe.com/page/design-tokens/)) & `components`

Acceptance Criteria
1. Modular structure - all categories of tokens must have a seperate `.scss` file
2. Documentation - JSDOC syntax to summarize the purpose of `.scss` file
3. Use BEM syntax for creation of class names
4. Use the latest version of SCSS & all of its new features (new Module System - @use, mixins, @each loop, functions, maps)
5. Configure [webpack](https://webpack.js.org/loaders/sass-loader/) `sass-loader`and related loaders to compile the above written SCSS files

**Comment by PS8924** [comment]
Just adding this typography file example for reference : 
1. [typography](https://gist.github.com/sebastiano-guerriero/2d05b319b9ae7618d99809797a67c0a0) 
2. [typography with mixins](https://medium.com/@cngzilhn/text-styles-best-practice-typography-scss-file-structure-24e8074ebfb4)
